package com.yinfires.icecore.oven;
import com.yinfires.icecore.ICECore;
import net.minecraft.world.item.*; import net.minecraft.world.level.block.*; import net.minecraft.world.level.block.state.BlockBehaviour; import net.minecraft.world.level.block.entity.*; import net.minecraft.world.level.block.state.properties.*; import net.minecraft.world.item.crafting.*; import net.minecraftforge.eventbus.api.IEventBus; import net.minecraftforge.registries.*;
public final class ModOven {
 public static final DeferredRegister<Block> BLOCKS=DeferredRegister.create(ForgeRegistries.BLOCKS,ICECore.MOD_ID); public static final DeferredRegister<Item> ITEMS=DeferredRegister.create(ForgeRegistries.ITEMS,ICECore.MOD_ID); public static final DeferredRegister<BlockEntityType<?>> ENTITIES=DeferredRegister.create(ForgeRegistries.BLOCK_ENTITY_TYPES,ICECore.MOD_ID); public static final DeferredRegister<RecipeType<?>> TYPES=DeferredRegister.create(ForgeRegistries.RECIPE_TYPES,ICECore.MOD_ID); public static final DeferredRegister<RecipeSerializer<?>> SERIALIZERS=DeferredRegister.create(ForgeRegistries.RECIPE_SERIALIZERS,ICECore.MOD_ID);
 public static final DirectionProperty FACING=BlockStateProperties.HORIZONTAL_FACING; public static final EnumProperty<OvenSupport> SUPPORT=EnumProperty.create("support",OvenSupport.class); public static final BooleanProperty WATERLOGGED=BlockStateProperties.WATERLOGGED;
 public static final RegistryObject<Block> OVEN=BLOCKS.register("oven",()->new OvenBlock(BlockBehaviour.Properties.of().strength(2).sound(SoundType.METAL).noOcclusion())); public static final RegistryObject<Item> OVEN_ITEM=ITEMS.register("oven",()->new BlockItem(OVEN.get(),new Item.Properties())); public static final RegistryObject<BlockEntityType<OvenBlockEntity>> OVEN_ENTITY=ENTITIES.register("oven",()->BlockEntityType.Builder.of(OvenBlockEntity::new,OVEN.get()).build(null)); public static final RegistryObject<RecipeType<OvenRecipe>> OVEN_RECIPE=TYPES.register("oven",()->new RecipeType<>(){}); public static final RegistryObject<RecipeSerializer<OvenRecipe>> OVEN_SERIALIZER=SERIALIZERS.register("oven",OvenRecipe.Serializer::new);
 public static void register(IEventBus b){BLOCKS.register(b);ITEMS.register(b);ENTITIES.register(b);TYPES.register(b);SERIALIZERS.register(b);} private ModOven(){}
}
