package com.yinfires.icecore.oven;
import com.yinfires.icecore.workstation.WorkstationContainerCompat;
import net.minecraft.network.Connection;
import net.minecraft.core.*; import net.minecraft.nbt.*; import net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket; import net.minecraft.server.level.ServerLevel; import net.minecraft.world.*; import net.minecraft.world.entity.player.Player; import net.minecraft.world.item.*; import net.minecraft.world.level.*; import net.minecraft.world.level.block.entity.*; import net.minecraft.world.level.block.state.BlockState; import java.util.*;
public final class OvenBlockEntity extends BlockEntity implements Container {
 public static final int CAPACITY=9; private final NonNullList<ItemStack> items=NonNullList.withSize(CAPACITY,ItemStack.EMPTY); private final NonNullList<ItemStack> containers=NonNullList.withSize(CAPACITY,ItemStack.EMPTY); private final long[] sequence=new long[CAPACITY]; private long next=1; private int stable; private int progress; private OvenRecipe active;
 public OvenBlockEntity(BlockPos p,BlockState s){super(ModOven.OVEN_ENTITY.get(),p,s);} public NonNullList<ItemStack> items(){return items;} public int progress(){return progress;} public boolean baking(){return active!=null;}
 public boolean addInput(ItemStack stack,ItemStack empty){if(firstEmpty()<0)return false; int i=firstEmpty(); items.set(i,stack.copyWithCount(1)); containers.set(i,empty.copyWithCount(1)); sequence[i]=next++; reset(); changed(); return true;}
 public ItemStack requiredLastContainer(){int found=-1;long newest=Long.MIN_VALUE;for(int i=0;i<CAPACITY;i++)if(!items.get(i).isEmpty()&&sequence[i]>newest){found=i;newest=sequence[i];}return found<0?ItemStack.EMPTY:containers.get(found).copy();}
 public ItemStack takeLast(ItemStack held,boolean container){int found=-1;long newest=Long.MIN_VALUE;for(int i=0;i<CAPACITY;i++)if(!items.get(i).isEmpty()&&sequence[i]>newest&&(!container||WorkstationContainerCompat.emptyMatches(containers.get(i),held))&& (container || containers.get(i).isEmpty())){found=i;newest=sequence[i];}if(found<0)return ItemStack.EMPTY;ItemStack r=items.get(found).copy();items.set(found,ItemStack.EMPTY);containers.set(found,ItemStack.EMPTY);sequence[found]=0;reset();changed();return r;}
 private void reset(){stable=0;progress=0;active=null;}
 public static void tick(Level l,BlockPos p,BlockState s,OvenBlockEntity o){if(l.isClientSide)return; if(!OvenHeatSourceCompat.isHeatSource(l,p)){o.active=null;o.progress=0;o.stable=0;return;} if(o.active==null){o.stable++;if(o.stable<100)return; o.active=o.findRecipe((ServerLevel)l);o.progress=0;if(o.active==null){o.stable=0;return;}} o.progress++;if(o.progress>=o.active.cookingTime()){o.finish((ServerLevel)l);}}
 private OvenRecipe findRecipe(ServerLevel l){SimpleContainer c=new SimpleContainer(items.toArray(ItemStack[]::new));for(OvenRecipe r:l.getRecipeManager().getAllRecipesFor(ModOven.OVEN_RECIPE.get())){var m=r.match(c,r.batch()?r.maxBatches():1);if(m.batches()>0&&canOutput(r,m.batches()))return r;}return null;}
 private boolean canOutput(OvenRecipe r,int batches){NonNullList<ItemStack> copy=NonNullList.create();copy.addAll(items);var m=r.match(new SimpleContainer(copy.toArray(ItemStack[]::new)),batches);for(int slot:m.slots())copy.set(slot,ItemStack.EMPTY);for(ItemStack out:r.results())for(int n=0;n<m.batches();n++)if(insert(copy,out)<0)return false;return true;}
 private static int insert(NonNullList<ItemStack> list,ItemStack in){for(int i=0;i<list.size();i++)if(list.get(i).isEmpty()){list.set(i,in.copyWithCount(1));return i;}return -1;}
 private void finish(ServerLevel l){SimpleContainer c=new SimpleContainer(items.toArray(ItemStack[]::new));var m=active.match(c,9);if(m.batches()<1||!canOutput(active,m.batches())){reset();return;}for(int slot:m.slots()){items.set(slot,ItemStack.EMPTY);containers.set(slot,ItemStack.EMPTY);sequence[slot]=0;}for(ItemStack out:active.results())for(int n=0;n<m.batches();n++){int slot=insert(items,out);if(slot>=0)sequence[slot]=next++;}reset();changed();}
 private int firstEmpty(){for(int i=0;i<CAPACITY;i++)if(items.get(i).isEmpty())return i;return -1;} @Override public int getContainerSize(){return CAPACITY;} @Override public boolean isEmpty(){return items.stream().allMatch(ItemStack::isEmpty);} @Override public ItemStack getItem(int i){return items.get(i);} @Override public ItemStack removeItem(int i,int n){ItemStack r=ContainerHelper.removeItem(items,i,n);if(!r.isEmpty()){containers.set(i,ItemStack.EMPTY);sequence[i]=0;reset();changed();}return r;} @Override public ItemStack removeItemNoUpdate(int i){ItemStack r=items.set(i,ItemStack.EMPTY);containers.set(i,ItemStack.EMPTY);sequence[i]=0;reset();changed();return r;} @Override public void setItem(int i,ItemStack s){items.set(i,s);reset();changed();} @Override public boolean stillValid(Player p){return Container.stillValidBlockEntity(this,p);} @Override public void clearContent(){items.clear();containers.clear();Arrays.fill(sequence,0);reset();changed();}
 @Override protected void saveAdditional(CompoundTag t){super.saveAdditional(t);ContainerHelper.saveAllItems(t,items);CompoundTag c=new CompoundTag();ContainerHelper.saveAllItems(c,containers);t.put("Containers",c);t.putInt("Stable",stable);t.putInt("Progress",progress);t.putLong("Next",next);t.putLongArray("Sequence",sequence);} @Override public void load(CompoundTag t){super.load(t);for(int i=0;i<CAPACITY;i++){items.set(i,ItemStack.EMPTY);containers.set(i,ItemStack.EMPTY);}Arrays.fill(sequence,0);ContainerHelper.loadAllItems(t,items);if(t.contains("Containers"))ContainerHelper.loadAllItems(t.getCompound("Containers"),containers);else for(int i=0;i<CAPACITY;i++){final int slot=i;WorkstationContainerCompat.describe(items.get(slot)).filter(e->e.behavior()==WorkstationContainerCompat.Behavior.INGREDIENT).ifPresent(e->containers.set(slot,e.empty().copy()));}stable=t.getInt("Stable");progress=t.getInt("Progress");next=Math.max(1,t.getLong("Next"));long[] a=t.getLongArray("Sequence");System.arraycopy(a,0,sequence,0,Math.min(a.length,CAPACITY));active=null;} @Override public ClientboundBlockEntityDataPacket getUpdatePacket(){return ClientboundBlockEntityDataPacket.create(this);}@Override public CompoundTag getUpdateTag(){return saveWithoutMetadata();}@Override public void onDataPacket(Connection c,ClientboundBlockEntityDataPacket p){if(p.getTag()!=null)load(p.getTag());}@Override public void handleUpdateTag(CompoundTag t){load(t);} private void changed(){setChanged();if(level!=null&&!level.isClientSide)level.sendBlockUpdated(worldPosition,getBlockState(),getBlockState(),3);}
}



