package com.yinfires.icecore.oven;
import com.yinfires.icecore.feedback.PlayerFeedback;
import com.yinfires.icecore.workstation.WorkstationContainerCompat;
import com.yinfires.icecore.workstation.WorkstationContainerInteraction;
import net.minecraft.core.*; import net.minecraft.core.particles.ParticleTypes; import net.minecraft.sounds.*; import net.minecraft.util.RandomSource; import net.minecraft.world.*; import net.minecraft.world.entity.player.Player; import net.minecraft.world.item.ItemStack; import net.minecraft.world.level.*; import net.minecraft.world.level.block.*; import net.minecraft.world.level.block.entity.*; import net.minecraft.world.level.block.state.*; import net.minecraft.world.level.material.*; import net.minecraft.world.phys.BlockHitResult; import javax.annotation.Nullable;
public final class OvenBlock extends BaseEntityBlock {
 public OvenBlock(Properties p){super(p);registerDefaultState(stateDefinition.any().setValue(ModOven.FACING,Direction.NORTH).setValue(ModOven.SUPPORT,OvenSupport.NONE).setValue(ModOven.WATERLOGGED,false));}
 @Override protected void createBlockStateDefinition(StateDefinition.Builder<Block,BlockState>b){b.add(ModOven.FACING,ModOven.SUPPORT,ModOven.WATERLOGGED);}
 @Override public BlockState getStateForPlacement(net.minecraft.world.item.context.BlockPlaceContext c){return defaultBlockState().setValue(ModOven.FACING,c.getHorizontalDirection().getOpposite()).setValue(ModOven.WATERLOGGED,c.getLevel().getFluidState(c.getClickedPos()).getType()==Fluids.WATER).setValue(ModOven.SUPPORT,support(c.getLevel(),c.getClickedPos()));}
 @Override public BlockState rotate(BlockState s,Rotation r){return s.setValue(ModOven.FACING,r.rotate(s.getValue(ModOven.FACING)));}
 @Override public BlockState mirror(BlockState s,Mirror m){return s.rotate(m.getRotation(s.getValue(ModOven.FACING)));}
 private static OvenSupport support(LevelReader l,BlockPos p){return OvenHeatSourceCompat.isHeatSource(l,p)?OvenSupport.TRAY:OvenSupport.NONE;}
 @Override public BlockState updateShape(BlockState s,Direction d,BlockState n,LevelAccessor l,BlockPos p,BlockPos np){return d==Direction.DOWN&&s.getValue(ModOven.SUPPORT)!=OvenSupport.HANDLE?s.setValue(ModOven.SUPPORT,support(l,p)):s;}
 @Override public FluidState getFluidState(BlockState s){return s.getValue(ModOven.WATERLOGGED)?Fluids.WATER.getSource(false):super.getFluidState(s);}
 @Override public RenderShape getRenderShape(BlockState s){return RenderShape.MODEL;} @Override public BlockEntity newBlockEntity(BlockPos p,BlockState s){return new OvenBlockEntity(p,s);}
 @Nullable @Override public <T extends BlockEntity> BlockEntityTicker<T> getTicker(Level l,BlockState s,BlockEntityType<T> t){return createTickerHelper(t,ModOven.OVEN_ENTITY.get(),OvenBlockEntity::tick);}
 @Override public void animateTick(BlockState s,Level l,BlockPos p,RandomSource r){if(OvenHeatSourceCompat.isHeatSource(l,p)&&r.nextInt(5)==0){Direction f=s.getValue(ModOven.FACING);double x=p.getX()+.5-f.getStepX()*.28;double z=p.getZ()+.5-f.getStepZ()*.28;l.addParticle(ParticleTypes.FLAME,x,p.getY()+.18,z,0,.02,0);}}
 @Override public InteractionResult use(BlockState s,Level l,BlockPos p,Player pl,InteractionHand h,BlockHitResult hit){if(l.isClientSide||!(l.getBlockEntity(p)instanceof OvenBlockEntity o))return l.isClientSide?InteractionResult.SUCCESS:InteractionResult.PASS;ItemStack held=pl.getItemInHand(h);if(held.isEmpty()){ItemStack r=o.takeLast(ItemStack.EMPTY,false);if(!r.isEmpty()){pl.setItemInHand(h,r);l.playSound(null,p,SoundEvents.ITEM_FRAME_REMOVE_ITEM,SoundSource.BLOCKS,.8F,1.1F);}else {ItemStack required=o.requiredLastContainer();if(!required.isEmpty())PlayerFeedback.show((net.minecraft.server.level.ServerPlayer)pl,net.minecraft.network.chat.Component.translatable("icecore.mixing.need_input_container",required.getHoverName()));}return InteractionResult.CONSUME;}if(WorkstationContainerCompat.isKnownEmptyContainer(held)){ItemStack r=o.takeLast(held,true);if(!r.isEmpty()){WorkstationContainerInteraction.exchange(pl,h,held,r);l.playSound(null,p,SoundEvents.ITEM_FRAME_REMOVE_ITEM,SoundSource.BLOCKS,.8F,1.1F);return InteractionResult.CONSUME;}}ItemStack empty=WorkstationContainerInteraction.requiredEmptyContainer(held,WorkstationContainerInteraction.FluidContainerMode.STORED_AS_ITEM);if(!o.addInput(held,empty))return InteractionResult.CONSUME;if(empty.isEmpty()){if(!pl.getAbilities().instabuild)held.shrink(1);}else WorkstationContainerInteraction.exchange(pl,h,held,empty);l.playSound(null,p,SoundEvents.ITEM_FRAME_ADD_ITEM,SoundSource.BLOCKS,.8F,1.1F);return InteractionResult.CONSUME;}
}
